# Generated by Django 6.0.3 on 2026-03-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="convertedfile",
            name="converted_audio",
            field=models.FileField(blank=True, null=True, upload_to="audio/"),
        ),
    ]
