# Generated by Django 6.0.3 on 2026-03-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_convertedfile_converted_audio"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="convertedfile",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="convertedfile",
            name="original_pdf",
        ),
        migrations.AddField(
            model_name="convertedfile",
            name="conversion_type",
            field=models.CharField(
                choices=[
                    ("tts", "Мәтін → Аудио"),
                    ("subtitles", "Видео → Субтитрлер"),
                    ("ocr", "Сурет → Мәтін"),
                    ("large_text", "Үлкен мәтін"),
                ],
                default="tts",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="convertedfile",
            name="converted_large_pdf",
            field=models.FileField(blank=True, null=True, upload_to="large_text/"),
        ),
        migrations.AddField(
            model_name="convertedfile",
            name="converted_subtitle",
            field=models.FileField(blank=True, null=True, upload_to="subtitles/"),
        ),
        migrations.AddField(
            model_name="convertedfile",
            name="converted_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="convertedfile",
            name="original_file",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
