# Generated by Django 6.0.3 on 2026-04-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_user_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermessage",
            name="replied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usermessage",
            name="reply",
            field=models.TextField(blank=True, null=True),
        ),
    ]
