# Generated by Django 6.0.3 on 2026-04-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_add_reply_to_usermessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="convertedfile",
            name="conversion_type",
            field=models.CharField(
                choices=[
                    ("tts", "Мәтін → Аудио"),
                    ("subtitles", "Видео → Субтитрлер"),
                    ("ocr", "Сурет → Мәтін"),
                    ("large_text", "Үлкен мәтін"),
                    ("braille", "Мәтін → Брайль"),
                ],
                default="tts",
                max_length=20,
            ),
        ),
    ]
